name: build-and-test
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Compose
        uses: ndeloof/install-docker-compose
        with:
          legacy: true
      - name: run docker build
        run: make build
      - name: test docker image
        run: make test
