name: build-and-push
on:
  push:
    branches:
      - 'master'
      - 'develop'

env:
  REGISTRY: ghcr.io
  REPO_PREFIX: scottaubrey/elifesciences-api-dummy
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Compose
        uses: ndeloof/install-compose-action@main
        with:
          legacy: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.9.1
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: run docker buildx and push images
        run: make IMAGE_TAG=${GITHUB_SHA} REPO_PREFIX=${{ env.REGISTRY }}/${{ env.REPO_PREFIX }} buildx-and-push
