name: build-and-test
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Compose
        uses: ndeloof/install-compose-action@main
        with:
          legacy: true
      - name: run docker build
        run: make build
      - name: test docker image
        run: make test
