name: build-and-test
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install Compose
        uses: ndeloof/install-compose-action@main
        with:
          legacy: true
      - name: run docker build
        run: make build
      - name: test docker image
        run: make test
